FROM phusion/baseimage:0.9.19 as builder

ENV LANG=en_US.UTF-8
ENV APPDIR /usr/local/src/viz/
ENV HOME /var/lib/vizd

RUN \
    apt-get update && \
    apt-get install -y \
        autoconf \
        automake \
        autotools-dev \
        bsdmainutils \
        build-essential \
        cmake \
        doxygen \
        git \
        ccache\
        libboost-all-dev \
        libreadline-dev \
        libssl-dev \
        libtool \
        ncurses-dev \
        pbzip2 \
        pkg-config \
        python3 \
        python3-dev \
        python3-pip && \
    pip3 install gcovr

# Explicitly copy needed files to avoid re-building when changing other files
COPY .git $APPDIR/.git
COPY .gitignore .gitmodules CMakeLists.txt Doxyfile $APPDIR/
COPY programs $APPDIR/programs
COPY thirdparty $APPDIR/thirdparty
COPY plugins $APPDIR/plugins
COPY libraries $APPDIR/libraries

RUN \
    cd $APPDIR && \
    git submodule deinit -f . && \
    git submodule update --init --recursive -f && \
    mkdir build && \
    cd build && \
    cmake \
        -DCMAKE_BUILD_TYPE=Release \
        -DBUILD_SHARED_LIBRARIES=FALSE \
        -DLOW_MEMORY_NODE=TRUE \
        -DCHAINBASE_CHECK_LOCKING=FALSE \
        -DENABLE_MONGO_PLUGIN=FALSE \
        .. \
    && \
    make -j$(nproc)

RUN set -xe ;\
    cd $APPDIR/build ;\
    make install ;\
    rm -rf $APPDIR

FROM phusion/baseimage:0.9.19
COPY --from=builder /usr/local /usr/local

RUN set -xe ;\
    useradd -s /bin/bash -m -d /var/lib/vizd vizd ;\
    mkdir /var/cache/vizd ;\
    chown vizd:vizd -R /var/cache/vizd

COPY share/vizd/vizd.sh /etc/service/vizd/run
COPY share/vizd/snapshot.json /var/lib/vizd
COPY share/vizd/config/config.ini /etc/vizd/config.ini
COPY share/vizd/seednodes /etc/vizd/seednodes

# rpc services:
# http
EXPOSE 8090
# ws
EXPOSE 8091
# p2p service:
EXPOSE 2001

VOLUME ["/var/lib/vizd", "/etc/vizd"]
